name: Test on macOS

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Cairo Setup
      run: brew install cairo
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test
